version: '3.8'

services:
  freeradius:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-localhost}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-radiusdb}
      MYSQL_USER: ${MYSQL_USER:-raduser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-passw0rd}
      DEFAULT_CLIENT_SECRET: ${DEFAULT_CLIENT_SECRET:-testing123}
    ports:
      - "${WEB_PORT:-8888}:80"  # daloRADIUS web interface
      - "${DA_API_PORT:-8000}:8000"  # daloRADIUS API
      - "${RADIUS_AUTH_PORT_UDP:-1812}:1812/udp"  # RADIUS authentication
      - "${RADIUS_ACCT_PORT_UDP:-1813}:1813/udp"  # RADIUS accounting
      - "${RADIUS_AUTH_PORT_TCP:-1812}:1812/tcp"  # RADIUS authentication (TCP)
      - "${RADIUS_ACCT_PORT_TCP:-1813}:1813/tcp"  # RADIUS accounting (TCP)
    volumes:
      - data:/data

volumes:
  data:
