version: '3.8'

services:
  freeradius:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DEFAULT_CLIENT_SECRET: ${DEFAULT_CLIENT_SECRET:-testing123}
      WEB_PORT: ${WEB_PORT:-8888}
      DA_API_PORT: ${DA_API_PORT:-8001}
      RADIUS_AUTH_PORT_UDP: ${RADIUS_AUTH_PORT_UDP:-1812}
      RADIUS_ACCT_PORT_UDP: ${RADIUS_ACCT_PORT_UDP:-1813}
      RADIUS_AUTH_PORT_TCP: ${RADIUS_AUTH_PORT_TCP:-1812}
      RADIUS_ACCT_PORT_TCP: ${RADIUS_ACCT_PORT_TCP:-1813}
    volumes:
      - data:/data

volumes:
  data:
